### ISSUE TITLE
How can I force override the font settings for this editor?

### ISSUE THREAD

**Issue by suhasinipr** [kmck/react-hex-editor#4]
I have this hex editor opening in another app screen in react js. The hex editor seems to take the font of the overall app and not the monospace that is specified in the theme for this editor. 
I've tried inline styles but even that doesn't work. 
Any suggestions on how I can override the font for hex editor to monospace regardless of the font in the rest of the app?

**Comment by kmck** [comment]
Do you have an example of the code you can share?

**Comment by suhasinipr** [comment]
Here is the component that has the hex editor.

```
return (
      
    <div style={divStyle}>
      <BaseHexEditor
      className="your-hex-editor"
      columns={0x10} // REQUIRED
      data={this.data}
      height={500} // REQUIRED
      // nonce={nonce}
      rowHeight={30} // REQUIRED
      rows={0x10} // REQUIRED
      onSetValue={this.handleSetValue}
      width={500} // REQUIRED
      showColumnLabels = {true}
      showRowLabels = {true}
      theme={{ hexEditor: myhexEditorTheme }}
      //inlineStyles={{row: {fontFamily: 'monospace'}}}
      />
    </div>
)
```

--- 
This is the styling I'm applying - 

index.styled.js - 

```
export const divStyle = {
  fontFamily: 'monospace',
};
export const myhexEditorTheme = {
  asciiPaddingX: 0,
  bytePaddingX: 0,
  rowPaddingY: '0.1em',
  colorBackground: '#282c34',
  colorBackgroundEven: '#282c34',
  colorBackgroundCursor: '#5c6370',
  colorBackgroundCursorHighlight: '#7f848e',
  colorBackgroundColumnEven: '#282c34',
  colorBackgroundColumnOdd: '#181a1f',
  colorBackgroundInactiveCursor: '#5c6370',
  colorBackgroundInactiveCursorHighlight: '#5c6370',
  colorBackgroundInactiveSelection: '#5c6370',
  colorBackgroundInactiveSelectionCursor: '#5c6370',
  colorBackgroundLabel: '#282c34',
  colorBackgroundLabelCurrent: '#282c34',
  colorBackgroundOdd: '#181a1f',
  colorBackgroundRowEven: '#282c34',
  colorBackgroundRowOdd: '#181a1f',
  colorBackgroundSelection: '#589bd3',
  colorBackgroundSelectionCursor: '#61afef',
  colorScrollbackTrack: '#282c34',
  colorScrollbackThumb: '#495162',
  colorScrollbackThumbHover: '#5c6370',
  colorText: '#abb2bf',
  colorTextEven: '#abb2bf',
  colorTextCursor: '#f8fafd',
  colorTextCursorHighlight: '#ffffff',
  colorTextColumnEven: '#abb2bf',
  colorTextColumnOdd: '#abb2bf',
  colorTextInactiveCursor: '#abb2bf',
  colorTextInactiveCursorHighlight: '#abb2bf',
  colorTextInactiveSelection: '#56b6c2',
  colorTextInactiveSelectionCursor: '#56b6c2',
  colorTextLabel: '#495162',
  colorTextLabelCurrent: '#737984',
  colorTextOdd: '#abb2bf',
  colorTextRowEven: '#abb2bf',
  colorTextRowOdd: '#abb2bf',
  colorTextSelection: '#d7dae0',
  colorTextSelectionCursor: '#ffffff',
  fontFamily: 'monospace' ,
  fontSize: '14px',
  gutterWidth: '2em',
  cursorBlinkSpeed: '0.5s',
  labelPaddingX: '0.1em',
  scrollWidth: 'auto',
  textTransform: 'uppercase',
};
```

---
style.scss ( for the main view). The following font-family setting is what is being actually applied to all views.  

```
* {
    font-family: Arial, "Avenir-Roman", sans-serif, monospace !important;
}

```
---
I added this style.scss file to try and override the main settings. But this doesn't work.
style.scss ( for this view )

```
* {
    font-family: monospace !important;
}
```

I checked the elements window and found that the second font-setting is striked off. 

![image](https://user-images.githubusercontent.com/29058094/96673879-26f37680-1385-11eb-9d10-88b3204be51a.png)

Is there some override setting I'm missing? 
Thank you for your time!

**Comment by kmck** [comment]
Using `*` will try to apply the style to every element individually, and `!important` means that it will clobber other styles, such as the ones from `myHexEditorTheme`. However, you have _two_ `!important` overrides, in which case I believe the last one wins, which is probably `font-family: Arial, ..., monospace !important`.

That said, I don't think you should need to style the hex editor with a scss file or use `!important` in the first place. If you need to style other things in the main view, try doing so without `!important` and/or without using the `*` selector. For example, if you're just trying to set a sans-serif font for the page that the hex editor can override, you might do something like this instead:

```scss
body {
  font-family: Arial, "Avenir-Roman", sans-serif;
}
```

**Comment by suhasinipr** [comment]
Ah. I thought that `font-family: monospace !important` would be the last one. 
Thanks for the clarification! 
Styling it with body instead of * works!
